// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olhyzbopzglgcksgfsww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9saHl6Ym9wemdsZ2Nrc2dmc3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzg3NjEsImV4cCI6MjA2OTY1NDc2MX0.iOx0Dbn1nRzNt7vPgCSPDLZg1g6znLNF6w5Uszrbqhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});